default: &default
  adapter: postgresql
  host: 127.0.0.1
  encoding: utf8
  pool: 5
  username: username
  password: password
  reconnect: false
  port: 5432

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
